updating
updateRootFonts: anHtmlRoot

	anHtmlRoot stylesheet url: (WAUrl absolute: 'https://fonts.googleapis.com/css?family=Roboto+Mono').
	anHtmlRoot stylesheet url: (WAUrl absolute: 'https://fonts.googleapis.com/css?family=Roboto:300,400,500').
	"anHtmlRoot stylesheet url: (WAUrl absolute: 'https://fonts.googleapis.com/icon?family=Material+Icons')."
	anHtmlRoot stylesheet url: 'https://fonts.googleapis.com/icon?family=Material+Icons'.
