accessing - fonts
buildFontChoices

	^{
MCWGoogleFont googleFontsFamily: 'Roboto+Condensed' familyName: 'Roboto Condensed' genericFamily: 'sans-serif'.
MCWGoogleFont googleFontsFamily: 'Roboto' familyName: 'Roboto' genericFamily: 'sans-serif'.
MCWGoogleFont googleFontsFamily: 'Bree+Serif' familyName: 'Bree Serif' genericFamily: 'serif'.
MCWGoogleFont googleFontsFamily: 'Open+Sans' familyName: 'Open Sans' genericFamily: 'sans-serif'.
MCWGoogleFont googleFontsFamily: 'Fontdiner+Swanky' familyName: 'Fontdiner Swanky' genericFamily: 'cursive'.
MCWGoogleFont googleFontsFamily: 'Pacifico' familyName: 'Pacifico' genericFamily: 'cursive'.
MCWGoogleFont googleFontsFamily: 'Oxygen+Mono' familyName: 'Oxygen Mono' genericFamily: 'monospace'.
	}