Extension { #name : #WATagBrush }

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcBanner [

	self class: 'mdc-banner'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcBanner__actions [

	self class: 'mdc-banner__actions'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcBanner__content [

	self class: 'mdc-banner__content'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcBanner__fixed [

	self class: 'mdc-banner__fixed'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcBanner__graphic [

	self class: 'mdc-banner__graphic'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcBanner__graphicTextWrapper [

	self class: 'mdc-banner__graphic-text-wrapper'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcBanner__icon [

	self class: 'mdc-banner__icon'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcBanner__secondaryAction [

	self class: 'mdc-banner__secondary-action'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcBanner__text [

	self class: 'mdc-banner__text'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcBanner_centered [

	self class: 'mdc-banner--centered'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcBanner_closing [

	self class: 'mdc-banner--closing'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcBanner_mobileStacked [

	self class: 'mdc-banner--mobile-stacked'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcBanner_open [

	self class: 'mdc-banner--open'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcBanner_opening [

	self class: 'mdc-banner--opening'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcButton [

	self class: 'mdc-button'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcButton__icon [

	self class: 'mdc-button__icon'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcButton__label [

	self class: 'mdc-button__label'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcButton__ripple [

	self class: 'mdc-button__ripple'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcButton__touch [

	self class: 'mdc-button__touch'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcButton_iconLeading [

	self class: 'mdc-button--icon-leading'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcButton_iconTrailing [

	self class: 'mdc-button--icon-trailing'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcButton_outlined [

	self class: 'mdc-button--outlined'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcButton_raised [

	self class: 'mdc-button--raised'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcButton_touch [

	self class: 'mdc-button--touch'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcButton_unelevated [

	self class: 'mdc-button--unelevated'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcCard [

	self class: 'mdc-card'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcCard__action [

	self class: 'mdc-card__action'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcCard__actionButtons [

	self class: 'mdc-card__action-buttons'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcCard__actionIcons [

	self class: 'mdc-card__action-icons'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcCard__action_button [

	self class: 'mdc-card__action--button'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcCard__action_icon [

	self class: 'mdc-card__action--icon'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcCard__actions [

	self class: 'mdc-card__actions'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcCard__actions_fullBleed [

	self class: 'mdc-card__actions--full-bleed'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcCard__content [

	self class: 'mdc-card__content'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcCard__media [

	self class: 'mdc-card__media'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcCard__mediaContent [

	self class: 'mdc-card__media-content'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcCard__media_square [

	self class: 'mdc-card__media--square'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcCard__media_v169 [

	self class: 'mdc-card__media--16-9'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcCard__primaryAction [

	self class: 'mdc-card__primary-action'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcCard__ripple [

	self class: 'mdc-card__ripple'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcCard_outlined [

	self class: 'mdc-card--outlined'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcCheckbox [

	self class: 'mdc-checkbox'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcCheckbox__background [

	self class: 'mdc-checkbox__background'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcCheckbox__checkmark [

	self class: 'mdc-checkbox__checkmark'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcCheckbox__checkmarkPath [

	self class: 'mdc-checkbox__checkmark-path'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcCheckbox__mixedmark [

	self class: 'mdc-checkbox__mixedmark'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcCheckbox__nativeControl [

	self class: 'mdc-checkbox__native-control'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcCheckbox__ripple [

	self class: 'mdc-checkbox__ripple'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcCheckbox_animCheckedIndeterminate [

	self class: 'mdc-checkbox--anim-checked-indeterminate'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcCheckbox_animCheckedUnchecked [

	self class: 'mdc-checkbox--anim-checked-unchecked'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcCheckbox_animIndeterminateChecked [

	self class: 'mdc-checkbox--anim-indeterminate-checked'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcCheckbox_animIndeterminateUnchecked [

	self class: 'mdc-checkbox--anim-indeterminate-unchecked'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcCheckbox_animUncheckedChecked [

	self class: 'mdc-checkbox--anim-unchecked-checked'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcCheckbox_animUncheckedIndeterminate [

	self class: 'mdc-checkbox--anim-unchecked-indeterminate'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcCheckbox_disabled [

	self class: 'mdc-checkbox--disabled'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcCheckbox_selected [

	self class: 'mdc-checkbox--selected'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcCheckbox_touch [

	self class: 'mdc-checkbox--touch'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcCheckbox_upgraded [

	self class: 'mdc-checkbox--upgraded'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcChip [

	self class: 'mdc-chip'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcChipSet [

	self class: 'mdc-chip-set'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcChipSet_choice [

	self class: 'mdc-chip-set--choice'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcChipSet_filter [

	self class: 'mdc-chip-set--filter'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcChipSet_input [

	self class: 'mdc-chip-set--input'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcChip__checkmark [

	self class: 'mdc-chip__checkmark'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcChip__checkmarkPath [

	self class: 'mdc-chip__checkmark-path'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcChip__checkmarkSvg [

	self class: 'mdc-chip__checkmark-svg'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcChip__icon [

	self class: 'mdc-chip__icon'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcChip__icon_leading [

	self class: 'mdc-chip__icon--leading'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcChip__icon_leadingHidden [

	self class: 'mdc-chip__icon--leading-hidden'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcChip__icon_trailing [

	self class: 'mdc-chip__icon--trailing'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcChip__overflow [

	self class: 'mdc-chip__overflow'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcChip__primaryAction [

	self class: 'mdc-chip__primary-action'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcChip__ripple [

	self class: 'mdc-chip__ripple'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcChip__text [

	self class: 'mdc-chip__text'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcChip__touch [

	self class: 'mdc-chip__touch'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcChip_exit [

	self class: 'mdc-chip--exit'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcChip_selected [

	self class: 'mdc-chip--selected'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcChip_touch [

	self class: 'mdc-chip--touch'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcCircularProgress [

	self class: 'mdc-circular-progress'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcCircularProgress__circleClipper [

	self class: 'mdc-circular-progress__circle-clipper'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcCircularProgress__circleLeft [

	self class: 'mdc-circular-progress__circle-left'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcCircularProgress__circleRight [

	self class: 'mdc-circular-progress__circle-right'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcCircularProgress__color1 [

	self class: 'mdc-circular-progress__color-1'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcCircularProgress__color2 [

	self class: 'mdc-circular-progress__color-2'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcCircularProgress__color3 [

	self class: 'mdc-circular-progress__color-3'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcCircularProgress__color4 [

	self class: 'mdc-circular-progress__color-4'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcCircularProgress__determinateCircle [

	self class: 'mdc-circular-progress__determinate-circle'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcCircularProgress__determinateCircleGraphic [

	self class: 'mdc-circular-progress__determinate-circle-graphic'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcCircularProgress__determinateContainer [

	self class: 'mdc-circular-progress__determinate-container'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcCircularProgress__determinateTrack [

	self class: 'mdc-circular-progress__determinate-track'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcCircularProgress__gapPatch [

	self class: 'mdc-circular-progress__gap-patch'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcCircularProgress__indeterminateCircleGraphic [

	self class: 'mdc-circular-progress__indeterminate-circle-graphic'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcCircularProgress__indeterminateContainer [

	self class: 'mdc-circular-progress__indeterminate-container'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcCircularProgress__spinnerLayer [

	self class: 'mdc-circular-progress__spinner-layer'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcCircularProgress_closed [

	self class: 'mdc-circular-progress--closed'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcCircularProgress_indeterminate [

	self class: 'mdc-circular-progress--indeterminate'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcDataTable [

	self class: 'mdc-data-table'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcDataTable__cell [

	self class: 'mdc-data-table__cell'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcDataTable__cell_checkbox [

	self class: 'mdc-data-table__cell--checkbox'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcDataTable__cell_numeric [

	self class: 'mdc-data-table__cell--numeric'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcDataTable__content [

	self class: 'mdc-data-table__content'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcDataTable__headerCell [

	self class: 'mdc-data-table__header-cell'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcDataTable__headerCellWrapper [

	self class: 'mdc-data-table__header-cell-wrapper'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcDataTable__headerCell_checkbox [

	self class: 'mdc-data-table__header-cell--checkbox'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcDataTable__headerCell_numeric [

	self class: 'mdc-data-table__header-cell--numeric'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcDataTable__headerCell_sorted [

	self class: 'mdc-data-table__header-cell--sorted'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcDataTable__headerCell_sortedDescending [

	self class: 'mdc-data-table__header-cell--sorted-descending'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcDataTable__headerCell_withSort [

	self class: 'mdc-data-table__header-cell--with-sort'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcDataTable__headerRow [

	self class: 'mdc-data-table__header-row'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcDataTable__headerRowCheckbox [

	self class: 'mdc-data-table__header-row-checkbox'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcDataTable__pagination [

	self class: 'mdc-data-table__pagination'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcDataTable__paginationButton [

	self class: 'mdc-data-table__pagination-button'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcDataTable__paginationNavigation [

	self class: 'mdc-data-table__pagination-navigation'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcDataTable__paginationRowsPerPage [

	self class: 'mdc-data-table__pagination-rows-per-page'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcDataTable__paginationRowsPerPageLabel [

	self class: 'mdc-data-table__pagination-rows-per-page-label'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcDataTable__paginationRowsPerPageSelect [

	self class: 'mdc-data-table__pagination-rows-per-page-select'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcDataTable__paginationTotal [

	self class: 'mdc-data-table__pagination-total'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcDataTable__paginationTrailing [

	self class: 'mdc-data-table__pagination-trailing'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcDataTable__progressIndicator [

	self class: 'mdc-data-table__progress-indicator'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcDataTable__row [

	self class: 'mdc-data-table__row'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcDataTable__rowCheckbox [

	self class: 'mdc-data-table__row-checkbox'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcDataTable__row_selected [

	self class: 'mdc-data-table__row--selected'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcDataTable__scrim [

	self class: 'mdc-data-table__scrim'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcDataTable__sortIconButton [

	self class: 'mdc-data-table__sort-icon-button'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcDataTable__sortStatusLabel [

	self class: 'mdc-data-table__sort-status-label'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcDataTable__table [

	self class: 'mdc-data-table__table'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcDataTable__tableContainer [

	self class: 'mdc-data-table__table-container'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcDataTable_inProgress [

	self class: 'mdc-data-table--in-progress'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcDataTable_stickyHeader [

	self class: 'mdc-data-table--sticky-header'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcDeprecatedList_dense [

	self class: 'mdc-deprecated-list--dense'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcDialog [

	self class: 'mdc-dialog'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcDialogScrollDividerFooter [

	self class: 'mdc-dialog-scroll-divider-footer'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcDialogScrollDividerHeader [

	self class: 'mdc-dialog-scroll-divider-header'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcDialogScrollLock [

	self class: 'mdc-dialog-scroll-lock'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcDialog__actions [

	self class: 'mdc-dialog__actions'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcDialog__button [

	self class: 'mdc-dialog__button'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcDialog__close [

	self class: 'mdc-dialog__close'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcDialog__container [

	self class: 'mdc-dialog__container'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcDialog__content [

	self class: 'mdc-dialog__content'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcDialog__header [

	self class: 'mdc-dialog__header'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcDialog__scrim [

	self class: 'mdc-dialog__scrim'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcDialog__scrim_hidden [

	self class: 'mdc-dialog__scrim--hidden'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcDialog__surface [

	self class: 'mdc-dialog__surface'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcDialog__surfaceScrim [

	self class: 'mdc-dialog__surface-scrim'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcDialog__surfaceScrim_hiding [

	self class: 'mdc-dialog__surface-scrim--hiding'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcDialog__surfaceScrim_showing [

	self class: 'mdc-dialog__surface-scrim--showing'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcDialog__surfaceScrim_shown [

	self class: 'mdc-dialog__surface-scrim--shown'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcDialog__title [

	self class: 'mdc-dialog__title'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcDialog__titleIcon [

	self class: 'mdc-dialog__title-icon'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcDialog_closing [

	self class: 'mdc-dialog--closing'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcDialog_fullscreen [

	self class: 'mdc-dialog--fullscreen'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcDialog_open [

	self class: 'mdc-dialog--open'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcDialog_opening [

	self class: 'mdc-dialog--opening'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcDialog_scrollable [

	self class: 'mdc-dialog--scrollable'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcDialog_stacked [

	self class: 'mdc-dialog--stacked'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcDrawer [

	self class: 'mdc-drawer'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcDrawerAppContent [

	self class: 'mdc-drawer-app-content'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcDrawerScrim [

	self class: 'mdc-drawer-scrim'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcDrawer__content [

	self class: 'mdc-drawer__content'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcDrawer__header [

	self class: 'mdc-drawer__header'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcDrawer__subtitle [

	self class: 'mdc-drawer__subtitle'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcDrawer__title [

	self class: 'mdc-drawer__title'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcDrawer_animate [

	self class: 'mdc-drawer--animate'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcDrawer_closing [

	self class: 'mdc-drawer--closing'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcDrawer_dismissible [

	self class: 'mdc-drawer--dismissible'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcDrawer_modal [

	self class: 'mdc-drawer--modal'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcDrawer_open [

	self class: 'mdc-drawer--open'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcDrawer_opening [

	self class: 'mdc-drawer--opening'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcElevationOverlay [

	self class: 'mdc-elevation-overlay'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcElevationTransition [

	self class: 'mdc-elevation-transition'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcElevation_z0 [

	self class: 'mdc-elevation--z0'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcElevation_z1 [

	self class: 'mdc-elevation--z1'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcElevation_z10 [

	self class: 'mdc-elevation--z10'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcElevation_z11 [

	self class: 'mdc-elevation--z11'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcElevation_z12 [

	self class: 'mdc-elevation--z12'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcElevation_z13 [

	self class: 'mdc-elevation--z13'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcElevation_z14 [

	self class: 'mdc-elevation--z14'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcElevation_z15 [

	self class: 'mdc-elevation--z15'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcElevation_z16 [

	self class: 'mdc-elevation--z16'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcElevation_z17 [

	self class: 'mdc-elevation--z17'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcElevation_z18 [

	self class: 'mdc-elevation--z18'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcElevation_z19 [

	self class: 'mdc-elevation--z19'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcElevation_z2 [

	self class: 'mdc-elevation--z2'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcElevation_z20 [

	self class: 'mdc-elevation--z20'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcElevation_z21 [

	self class: 'mdc-elevation--z21'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcElevation_z22 [

	self class: 'mdc-elevation--z22'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcElevation_z23 [

	self class: 'mdc-elevation--z23'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcElevation_z24 [

	self class: 'mdc-elevation--z24'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcElevation_z3 [

	self class: 'mdc-elevation--z3'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcElevation_z4 [

	self class: 'mdc-elevation--z4'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcElevation_z5 [

	self class: 'mdc-elevation--z5'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcElevation_z6 [

	self class: 'mdc-elevation--z6'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcElevation_z7 [

	self class: 'mdc-elevation--z7'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcElevation_z8 [

	self class: 'mdc-elevation--z8'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcElevation_z9 [

	self class: 'mdc-elevation--z9'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcFab [

	self class: 'mdc-fab'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcFab__icon [

	self class: 'mdc-fab__icon'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcFab__label [

	self class: 'mdc-fab__label'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcFab__ripple [

	self class: 'mdc-fab__ripple'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcFab__touch [

	self class: 'mdc-fab__touch'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcFab_exited [

	self class: 'mdc-fab--exited'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcFab_extended [

	self class: 'mdc-fab--extended'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcFab_mini [

	self class: 'mdc-fab--mini'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcFab_touch [

	self class: 'mdc-fab--touch'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcFloatingLabel [

	self class: 'mdc-floating-label'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcFloatingLabel_floatAbove [

	self class: 'mdc-floating-label--float-above'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcFloatingLabel_required [

	self class: 'mdc-floating-label--required'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcFloatingLabel_shake [

	self class: 'mdc-floating-label--shake'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcFormField [

	self class: 'mdc-form-field'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcFormField_alignEnd [

	self class: 'mdc-form-field--align-end'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcFormField_nowrap [

	self class: 'mdc-form-field--nowrap'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcFormField_spaceBetween [

	self class: 'mdc-form-field--space-between'
]

{ #category : #'*Material-Web-Core' }
WATagBrush class >> mdcGenerateCssToMdcDatShell [
	"Copy the shell script in the comment below to css-to-list.sh - remember to change
	the doubled double-quote's to single double-quote's.
	Make the file executable, and run it with input file from material design .css file.

	For example:
	1. curl -L https://unpkg.com/material-components-web@latest/dist/material-components-web.css > mdc.css
	2. ./css-to-list.sh < mdc.css > mdc.dat
	3. use mdc.dat when invoking #mdcGenerateTagsFrom:
			self mdcGenerateTagsFrom: 'mdc.dat'
	"

	"
sed ""s/^ *//"" $1 \
| grep '^\.mdc-' \
| awk -F' ' '{for (i = 0; ++i <= NF;) print $i}' \
| awk -F',' '{for (i = 0; ++i <= NF;) print $i}' \
| awk -F'+' '{for (i = 0; ++i <= NF;) print $i}' \
| awk -F'>' '{for (i = 0; ++i <= NF;) print $i}' \
| awk -F'.' '{for (i = 0; ++i <= NF;) print $i}' \
| grep '^mdc-' \
| sed -e 's/[:\[].*//' \
| sed -e 's/[~)]$//' \
| sort -u
	"
]

{ #category : #'*Material-Web-Core' }
WATagBrush class >> mdcGenerateMethod: aCssClass [
	| selectorName code |

	selectorName := self mdcGenerateMethodName: aCssClass.
	Transcript crShow: selectorName; show: ' <<<< '; show: aCssClass.

	code := selectorName, (String with: Character cr), (String with: Character cr), (String with: Character tab), 'self class: ', aCssClass printString.

	self compile: code classified: '*Material-Web-Core'
]

{ #category : #'*Material-Web-Core' }
WATagBrush class >> mdcGenerateMethodName: aCssClass [
	| selectorName blockPart elementPart modifierPart index |

	blockPart := aCssClass.
	elementPart := ''.
	modifierPart := ''.

	index := blockPart findString: '__'.
	index > 0 ifTrue: [
		elementPart := blockPart copyFrom: index + 2 to: blockPart size.
		blockPart := blockPart copyFrom: 1 to: index ].

	index := elementPart findString: '--'.
	index > 0 ifTrue: [
		modifierPart := elementPart copyFrom: index + 2 to: elementPart size.
		elementPart := elementPart copyFrom: 1 to: index ].

	index := blockPart findString: '--'.
	index > 0 ifTrue: [
		modifierPart := blockPart copyFrom: index + 2 to: blockPart size.
		blockPart := blockPart copyFrom: 1 to: index ].

	selectorName := ''.
	blockPart notEmpty ifTrue: [
		selectorName := selectorName, (self mdcGenerateSelectorFragment: blockPart) ].

	elementPart notEmpty ifTrue: [
		selectorName := selectorName, '__', (self mdcGenerateSelectorFragment: elementPart) ].

	modifierPart notEmpty ifTrue: [
		selectorName := selectorName, '_', (self mdcGenerateSelectorFragment: modifierPart) ].

	^ selectorName
]

{ #category : #'*Material-Web-Core' }
WATagBrush class >> mdcGenerateSelectorFragment: aBlockElementModifierPart [
	"
	(self mdcGenerateSelectorFragment: 'aaa-bbb-ccc') = 'aaaBbbCcc'
	"

	^ ('' join: ((aBlockElementModifierPart substrings: '-') collect: [ :each | each asCamelCase ])) asValidSelector

]

{ #category : #'*Material-Web-Core' }
WATagBrush class >> mdcGenerateTagsFrom: aFilename [
	"
	MDC uses BEM naming convention:
		.block {}
		.block__element {}
		.block--modifier {}

	self generateMdcTagsFrom: 'test.dat'

aaaBbbCcc <<<< aaa-bbb-ccc
aaaBbbCcc_eeeFffGgg <<<< aaa-bbb-ccc__eee-fff-ggg
aaaBbbCcc__xxxYyyZzz <<<< aaa-bbb-ccc--xxx-yyy-zzz
aaaBbbCcc_eeeFffGgg__xxxYyyZzz <<<< aaa-bbb-ccc__eee-fff-ggg--xxx-yyy-zzz

	self mdcGenerateTagsFrom: '../../material-design/mdc.dat'
	"
	| reference |

	reference := FileSystem disk workingDirectory / aFilename.
	reference readStreamDo: [ :stream |
		[ stream atEnd ] whileFalse: [
			| nextLine |
			nextLine := stream upTo: Character lf.
			self mdcGenerateMethod: nextLine
		].
	]
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcIconButton [

	self class: 'mdc-icon-button'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcIconButton__icon [

	self class: 'mdc-icon-button__icon'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcIconButton__icon_on [

	self class: 'mdc-icon-button__icon--on'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcIconButton__ripple [

	self class: 'mdc-icon-button__ripple'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcIconButton__touch [

	self class: 'mdc-icon-button__touch'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcIconButton_displayFlex [

	self class: 'mdc-icon-button--display-flex'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcIconButton_on [

	self class: 'mdc-icon-button--on'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcIconButton_reducedSize [

	self class: 'mdc-icon-button--reduced-size'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcIconButton_touch [

	self class: 'mdc-icon-button--touch'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcImageList [

	self class: 'mdc-image-list'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcImageList__image [

	self class: 'mdc-image-list__image'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcImageList__imageAspectContainer [

	self class: 'mdc-image-list__image-aspect-container'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcImageList__item [

	self class: 'mdc-image-list__item'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcImageList__label [

	self class: 'mdc-image-list__label'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcImageList__supporting [

	self class: 'mdc-image-list__supporting'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcImageList_masonry [

	self class: 'mdc-image-list--masonry'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcImageList_withTextProtection [

	self class: 'mdc-image-list--with-text-protection'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLayoutGrid [

	self class: 'mdc-layout-grid'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLayoutGrid__cell [

	self class: 'mdc-layout-grid__cell'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLayoutGrid__cell_alignBottom [

	self class: 'mdc-layout-grid__cell--align-bottom'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLayoutGrid__cell_alignMiddle [

	self class: 'mdc-layout-grid__cell--align-middle'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLayoutGrid__cell_alignTop [

	self class: 'mdc-layout-grid__cell--align-top'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLayoutGrid__cell_order1 [

	self class: 'mdc-layout-grid__cell--order-1'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLayoutGrid__cell_order10 [

	self class: 'mdc-layout-grid__cell--order-10'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLayoutGrid__cell_order11 [

	self class: 'mdc-layout-grid__cell--order-11'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLayoutGrid__cell_order12 [

	self class: 'mdc-layout-grid__cell--order-12'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLayoutGrid__cell_order2 [

	self class: 'mdc-layout-grid__cell--order-2'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLayoutGrid__cell_order3 [

	self class: 'mdc-layout-grid__cell--order-3'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLayoutGrid__cell_order4 [

	self class: 'mdc-layout-grid__cell--order-4'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLayoutGrid__cell_order5 [

	self class: 'mdc-layout-grid__cell--order-5'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLayoutGrid__cell_order6 [

	self class: 'mdc-layout-grid__cell--order-6'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLayoutGrid__cell_order7 [

	self class: 'mdc-layout-grid__cell--order-7'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLayoutGrid__cell_order8 [

	self class: 'mdc-layout-grid__cell--order-8'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLayoutGrid__cell_order9 [

	self class: 'mdc-layout-grid__cell--order-9'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLayoutGrid__cell_span1 [

	self class: 'mdc-layout-grid__cell--span-1'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLayoutGrid__cell_span10 [

	self class: 'mdc-layout-grid__cell--span-10'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLayoutGrid__cell_span10Desktop [

	self class: 'mdc-layout-grid__cell--span-10-desktop'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLayoutGrid__cell_span10Phone [

	self class: 'mdc-layout-grid__cell--span-10-phone'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLayoutGrid__cell_span10Tablet [

	self class: 'mdc-layout-grid__cell--span-10-tablet'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLayoutGrid__cell_span11 [

	self class: 'mdc-layout-grid__cell--span-11'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLayoutGrid__cell_span11Desktop [

	self class: 'mdc-layout-grid__cell--span-11-desktop'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLayoutGrid__cell_span11Phone [

	self class: 'mdc-layout-grid__cell--span-11-phone'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLayoutGrid__cell_span11Tablet [

	self class: 'mdc-layout-grid__cell--span-11-tablet'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLayoutGrid__cell_span12 [

	self class: 'mdc-layout-grid__cell--span-12'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLayoutGrid__cell_span12Desktop [

	self class: 'mdc-layout-grid__cell--span-12-desktop'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLayoutGrid__cell_span12Phone [

	self class: 'mdc-layout-grid__cell--span-12-phone'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLayoutGrid__cell_span12Tablet [

	self class: 'mdc-layout-grid__cell--span-12-tablet'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLayoutGrid__cell_span1Desktop [

	self class: 'mdc-layout-grid__cell--span-1-desktop'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLayoutGrid__cell_span1Phone [

	self class: 'mdc-layout-grid__cell--span-1-phone'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLayoutGrid__cell_span1Tablet [

	self class: 'mdc-layout-grid__cell--span-1-tablet'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLayoutGrid__cell_span2 [

	self class: 'mdc-layout-grid__cell--span-2'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLayoutGrid__cell_span2Desktop [

	self class: 'mdc-layout-grid__cell--span-2-desktop'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLayoutGrid__cell_span2Phone [

	self class: 'mdc-layout-grid__cell--span-2-phone'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLayoutGrid__cell_span2Tablet [

	self class: 'mdc-layout-grid__cell--span-2-tablet'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLayoutGrid__cell_span3 [

	self class: 'mdc-layout-grid__cell--span-3'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLayoutGrid__cell_span3Desktop [

	self class: 'mdc-layout-grid__cell--span-3-desktop'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLayoutGrid__cell_span3Phone [

	self class: 'mdc-layout-grid__cell--span-3-phone'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLayoutGrid__cell_span3Tablet [

	self class: 'mdc-layout-grid__cell--span-3-tablet'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLayoutGrid__cell_span4 [

	self class: 'mdc-layout-grid__cell--span-4'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLayoutGrid__cell_span4Desktop [

	self class: 'mdc-layout-grid__cell--span-4-desktop'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLayoutGrid__cell_span4Phone [

	self class: 'mdc-layout-grid__cell--span-4-phone'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLayoutGrid__cell_span4Tablet [

	self class: 'mdc-layout-grid__cell--span-4-tablet'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLayoutGrid__cell_span5 [

	self class: 'mdc-layout-grid__cell--span-5'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLayoutGrid__cell_span5Desktop [

	self class: 'mdc-layout-grid__cell--span-5-desktop'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLayoutGrid__cell_span5Phone [

	self class: 'mdc-layout-grid__cell--span-5-phone'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLayoutGrid__cell_span5Tablet [

	self class: 'mdc-layout-grid__cell--span-5-tablet'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLayoutGrid__cell_span6 [

	self class: 'mdc-layout-grid__cell--span-6'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLayoutGrid__cell_span6Desktop [

	self class: 'mdc-layout-grid__cell--span-6-desktop'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLayoutGrid__cell_span6Phone [

	self class: 'mdc-layout-grid__cell--span-6-phone'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLayoutGrid__cell_span6Tablet [

	self class: 'mdc-layout-grid__cell--span-6-tablet'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLayoutGrid__cell_span7 [

	self class: 'mdc-layout-grid__cell--span-7'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLayoutGrid__cell_span7Desktop [

	self class: 'mdc-layout-grid__cell--span-7-desktop'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLayoutGrid__cell_span7Phone [

	self class: 'mdc-layout-grid__cell--span-7-phone'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLayoutGrid__cell_span7Tablet [

	self class: 'mdc-layout-grid__cell--span-7-tablet'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLayoutGrid__cell_span8 [

	self class: 'mdc-layout-grid__cell--span-8'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLayoutGrid__cell_span8Desktop [

	self class: 'mdc-layout-grid__cell--span-8-desktop'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLayoutGrid__cell_span8Phone [

	self class: 'mdc-layout-grid__cell--span-8-phone'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLayoutGrid__cell_span8Tablet [

	self class: 'mdc-layout-grid__cell--span-8-tablet'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLayoutGrid__cell_span9 [

	self class: 'mdc-layout-grid__cell--span-9'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLayoutGrid__cell_span9Desktop [

	self class: 'mdc-layout-grid__cell--span-9-desktop'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLayoutGrid__cell_span9Phone [

	self class: 'mdc-layout-grid__cell--span-9-phone'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLayoutGrid__cell_span9Tablet [

	self class: 'mdc-layout-grid__cell--span-9-tablet'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLayoutGrid__inner [

	self class: 'mdc-layout-grid__inner'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLayoutGrid_alignLeft [

	self class: 'mdc-layout-grid--align-left'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLayoutGrid_alignRight [

	self class: 'mdc-layout-grid--align-right'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLayoutGrid_fixedColumnWidth [

	self class: 'mdc-layout-grid--fixed-column-width'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLineRipple [

	self class: 'mdc-line-ripple'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLineRipple_active [

	self class: 'mdc-line-ripple--active'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLineRipple_deactivating [

	self class: 'mdc-line-ripple--deactivating'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLinearProgress [

	self class: 'mdc-linear-progress'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLinearProgress__bar [

	self class: 'mdc-linear-progress__bar'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLinearProgress__barInner [

	self class: 'mdc-linear-progress__bar-inner'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLinearProgress__buffer [

	self class: 'mdc-linear-progress__buffer'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLinearProgress__bufferBar [

	self class: 'mdc-linear-progress__buffer-bar'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLinearProgress__bufferDots [

	self class: 'mdc-linear-progress__buffer-dots'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLinearProgress__primaryBar [

	self class: 'mdc-linear-progress__primary-bar'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLinearProgress__secondaryBar [

	self class: 'mdc-linear-progress__secondary-bar'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLinearProgress_animationReady [

	self class: 'mdc-linear-progress--animation-ready'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLinearProgress_closed [

	self class: 'mdc-linear-progress--closed'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLinearProgress_closedAnimationOff [

	self class: 'mdc-linear-progress--closed-animation-off'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcLinearProgress_indeterminate [

	self class: 'mdc-linear-progress--indeterminate'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcList [

	self class: 'mdc-list'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcListDivider [

	self class: 'mdc-list-divider'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcListDivider_withLeadingAvatar [

	self class: 'mdc-list-divider--with-leading-avatar'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcListDivider_withLeadingCheckbox [

	self class: 'mdc-list-divider--with-leading-checkbox'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcListDivider_withLeadingIcon [

	self class: 'mdc-list-divider--with-leading-icon'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcListDivider_withLeadingImage [

	self class: 'mdc-list-divider--with-leading-image'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcListDivider_withLeadingInset [

	self class: 'mdc-list-divider--with-leading-inset'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcListDivider_withLeadingRadio [

	self class: 'mdc-list-divider--with-leading-radio'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcListDivider_withLeadingSwitch [

	self class: 'mdc-list-divider--with-leading-switch'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcListDivider_withLeadingText [

	self class: 'mdc-list-divider--with-leading-text'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcListDivider_withLeadingThumbnail [

	self class: 'mdc-list-divider--with-leading-thumbnail'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcListDivider_withLeadingVideo [

	self class: 'mdc-list-divider--with-leading-video'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcListDivider_withTrailingInset [

	self class: 'mdc-list-divider--with-trailing-inset'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcListGroup [

	self class: 'mdc-list-group'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcListGroup__subheader [

	self class: 'mdc-list-group__subheader'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcListItem [

	self class: 'mdc-list-item'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcListItem__content [

	self class: 'mdc-list-item__content'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcListItem__end [

	self class: 'mdc-list-item__end'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcListItem__graphic [

	self class: 'mdc-list-item__graphic'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcListItem__meta [

	self class: 'mdc-list-item__meta'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcListItem__overlineText [

	self class: 'mdc-list-item__overline-text'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcListItem__primaryText [

	self class: 'mdc-list-item__primary-text'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcListItem__ripple [

	self class: 'mdc-list-item__ripple'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcListItem__secondaryText [

	self class: 'mdc-list-item__secondary-text'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcListItem__start [

	self class: 'mdc-list-item__start'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcListItem__text [

	self class: 'mdc-list-item__text'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcListItem_activated [

	self class: 'mdc-list-item--activated'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcListItem_disabled [

	self class: 'mdc-list-item--disabled'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcListItem_nonInteractive [

	self class: 'mdc-list-item--non-interactive'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcListItem_selected [

	self class: 'mdc-list-item--selected'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcListItem_withLeadingAvatar [

	self class: 'mdc-list-item--with-leading-avatar'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcListItem_withLeadingCheckbox [

	self class: 'mdc-list-item--with-leading-checkbox'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcListItem_withLeadingIcon [

	self class: 'mdc-list-item--with-leading-icon'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcListItem_withLeadingImage [

	self class: 'mdc-list-item--with-leading-image'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcListItem_withLeadingRadio [

	self class: 'mdc-list-item--with-leading-radio'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcListItem_withLeadingSwitch [

	self class: 'mdc-list-item--with-leading-switch'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcListItem_withLeadingThumbnail [

	self class: 'mdc-list-item--with-leading-thumbnail'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcListItem_withLeadingVideo [

	self class: 'mdc-list-item--with-leading-video'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcListItem_withOneLine [

	self class: 'mdc-list-item--with-one-line'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcListItem_withOverline [

	self class: 'mdc-list-item--with-overline'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcListItem_withThreeLines [

	self class: 'mdc-list-item--with-three-lines'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcListItem_withTrailingCheckbox [

	self class: 'mdc-list-item--with-trailing-checkbox'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcListItem_withTrailingIcon [

	self class: 'mdc-list-item--with-trailing-icon'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcListItem_withTrailingMeta [

	self class: 'mdc-list-item--with-trailing-meta'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcListItem_withTrailingRadio [

	self class: 'mdc-list-item--with-trailing-radio'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcListItem_withTrailingSwitch [

	self class: 'mdc-list-item--with-trailing-switch'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcListItem_withTwoLines [

	self class: 'mdc-list-item--with-two-lines'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcList_dense [

	self mdcDeprecatedList_dense
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcList_imageList [

	self class: 'mdc-list--image-list'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcList_twoLine [

	self class: 'mdc-list--two-line'
]

{ #category : #'*Material-Web-Core-extra' }
WATagBrush >> mdcMaterialIcons [

	self class: 'material-icons'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcMenu [

	self class: 'mdc-menu'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcMenuItem_selected [

	self class: 'mdc-menu-item--selected'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcMenuSurface [

	self class: 'mdc-menu-surface'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcMenuSurface_anchor [

	self class: 'mdc-menu-surface--anchor'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcMenuSurface_animatingClosed [

	self class: 'mdc-menu-surface--animating-closed'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcMenuSurface_animatingOpen [

	self class: 'mdc-menu-surface--animating-open'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcMenuSurface_fixed [

	self class: 'mdc-menu-surface--fixed'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcMenuSurface_fullwidth [

	self class: 'mdc-menu-surface--fullwidth'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcMenuSurface_isOpenBelow [

	self class: 'mdc-menu-surface--is-open-below'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcMenuSurface_open [

	self class: 'mdc-menu-surface--open'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcMenu__selectionGroup [

	self class: 'mdc-menu__selection-group'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcMenu__selectionGroupIcon [

	self class: 'mdc-menu__selection-group-icon'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcNotchedOutline [

	self class: 'mdc-notched-outline'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcNotchedOutline__leading [

	self class: 'mdc-notched-outline__leading'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcNotchedOutline__notch [

	self class: 'mdc-notched-outline__notch'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcNotchedOutline__trailing [

	self class: 'mdc-notched-outline__trailing'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcNotchedOutline_noLabel [

	self class: 'mdc-notched-outline--no-label'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcNotchedOutline_notched [

	self class: 'mdc-notched-outline--notched'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcNotchedOutline_upgraded [

	self class: 'mdc-notched-outline--upgraded'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcRadio [

	self class: 'mdc-radio'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcRadio__background [

	self class: 'mdc-radio__background'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcRadio__innerCircle [

	self class: 'mdc-radio__inner-circle'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcRadio__nativeControl [

	self class: 'mdc-radio__native-control'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcRadio__outerCircle [

	self class: 'mdc-radio__outer-circle'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcRadio__ripple [

	self class: 'mdc-radio__ripple'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcRadio_disabled [

	self class: 'mdc-radio--disabled'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcRadio_touch [

	self class: 'mdc-radio--touch'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcRippleSurface [

	self class: 'mdc-ripple-surface'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcRippleSurface_hover [

	self class: 'mdc-ripple-surface--hover'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcRippleUpgraded [

	self class: 'mdc-ripple-upgraded'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcRippleUpgraded_backgroundFocused [

	self class: 'mdc-ripple-upgraded--background-focused'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcRippleUpgraded_foregroundActivation [

	self class: 'mdc-ripple-upgraded--foreground-activation'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcRippleUpgraded_foregroundDeactivation [

	self class: 'mdc-ripple-upgraded--foreground-deactivation'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcRippleUpgraded_unbounded [

	self class: 'mdc-ripple-upgraded--unbounded'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcSegmentedButton [

	self class: 'mdc-segmented-button'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcSegmentedButton__icon [

	self class: 'mdc-segmented-button__icon'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcSegmentedButton__label [

	self class: 'mdc-segmented-button__label'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcSegmentedButton__ripple [

	self class: 'mdc-segmented-button__ripple'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcSegmentedButton__segment [

	self class: 'mdc-segmented-button__segment'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcSegmentedButton__segment_selected [

	self class: 'mdc-segmented-button__segment--selected'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcSegmentedButton__segment_touch [

	self class: 'mdc-segmented-button__segment--touch'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcSegmentedButton__segmenttouch [

	self class: 'mdc-segmented-button__segment__touch'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcSelect [

	self class: 'mdc-select'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcSelectHelperText [

	self class: 'mdc-select-helper-text'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcSelectHelperText_validationMsg [

	self class: 'mdc-select-helper-text--validation-msg'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcSelectHelperText_validationMsgPersistent [

	self class: 'mdc-select-helper-text--validation-msg-persistent'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcSelect__anchor [

	self class: 'mdc-select__anchor'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcSelect__dropdownIcon [

	self class: 'mdc-select__dropdown-icon'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcSelect__dropdownIconActive [

	self class: 'mdc-select__dropdown-icon-active'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcSelect__dropdownIconGraphic [

	self class: 'mdc-select__dropdown-icon-graphic'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcSelect__dropdownIconInactive [

	self class: 'mdc-select__dropdown-icon-inactive'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcSelect__icon [

	self class: 'mdc-select__icon'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcSelect__menu [

	self class: 'mdc-select__menu'
]

{ #category : #'*Material-Web-Core-generated' }
WATagBrush >> mdcSelect__nativeControl [

	self class: 'mdc-select__native-control'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcSelect__oneLineOption [

	self class: 'mdc-select__one-line-option'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcSelect__option [

	self class: 'mdc-select__option'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcSelect__optionWithLeadingContent [

	self class: 'mdc-select__option-with-leading-content'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcSelect__optionWithMeta [

	self class: 'mdc-select__option-with-meta'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcSelect__ripple [

	self class: 'mdc-select__ripple'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcSelect__selectedText [

	self class: 'mdc-select__selected-text'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcSelect__selectedTextContainer [

	self class: 'mdc-select__selected-text-container'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcSelect__twoLineOption [

	self class: 'mdc-select__two-line-option'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcSelect_activated [

	self class: 'mdc-select--activated'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcSelect_disabled [

	self class: 'mdc-select--disabled'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcSelect_filled [

	self class: 'mdc-select--filled'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcSelect_focused [

	self class: 'mdc-select--focused'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcSelect_invalid [

	self class: 'mdc-select--invalid'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcSelect_noLabel [

	self class: 'mdc-select--no-label'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcSelect_outlined [

	self class: 'mdc-select--outlined'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcSelect_withLeadingIcon [

	self class: 'mdc-select--with-leading-icon'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcSlider [

	self class: 'mdc-slider'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcSlider__input [

	self class: 'mdc-slider__input'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcSlider__thumb [

	self class: 'mdc-slider__thumb'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcSlider__thumbKnob [

	self class: 'mdc-slider__thumb-knob'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcSlider__thumb_focused [

	self class: 'mdc-slider__thumb--focused'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcSlider__thumb_top [

	self class: 'mdc-slider__thumb--top'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcSlider__thumb_withIndicator [

	self class: 'mdc-slider__thumb--with-indicator'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcSlider__tickMark_active [

	self class: 'mdc-slider__tick-mark--active'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcSlider__tickMark_inactive [

	self class: 'mdc-slider__tick-mark--inactive'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcSlider__tickMarks [

	self class: 'mdc-slider__tick-marks'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcSlider__track [

	self class: 'mdc-slider__track'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcSlider__track_active [

	self class: 'mdc-slider__track--active'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcSlider__track_activefill [

	self class: 'mdc-slider__track--active_fill'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcSlider__track_inactive [

	self class: 'mdc-slider__track--inactive'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcSlider__valueIndicator [

	self class: 'mdc-slider__value-indicator'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcSlider__valueIndicatorContainer [

	self class: 'mdc-slider__value-indicator-container'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcSlider__valueIndicatorText [

	self class: 'mdc-slider__value-indicator-text'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcSlider_disabled [

	self class: 'mdc-slider--disabled'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcSlider_discrete [

	self class: 'mdc-slider--discrete'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcSnackbar [

	self class: 'mdc-snackbar'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcSnackbar__action [

	self class: 'mdc-snackbar__action'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcSnackbar__actions [

	self class: 'mdc-snackbar__actions'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcSnackbar__dismiss [

	self class: 'mdc-snackbar__dismiss'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcSnackbar__label [

	self class: 'mdc-snackbar__label'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcSnackbar__surface [

	self class: 'mdc-snackbar__surface'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcSnackbar_closing [

	self class: 'mdc-snackbar--closing'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcSnackbar_leading [

	self class: 'mdc-snackbar--leading'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcSnackbar_open [

	self class: 'mdc-snackbar--open'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcSnackbar_opening [

	self class: 'mdc-snackbar--opening'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcSnackbar_stacked [

	self class: 'mdc-snackbar--stacked'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcSwitch [

	self class: 'mdc-switch'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcSwitch__handle [

	self class: 'mdc-switch__handle'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcSwitch__handleTrack [

	self class: 'mdc-switch__handle-track'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcSwitch__icon [

	self class: 'mdc-switch__icon'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcSwitch__icon_off [

	self class: 'mdc-switch__icon--off'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcSwitch__icon_on [

	self class: 'mdc-switch__icon--on'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcSwitch__icons [

	self class: 'mdc-switch__icons'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcSwitch__ripple [

	self class: 'mdc-switch__ripple'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcSwitch__shadow [

	self class: 'mdc-switch__shadow'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcSwitch__track [

	self class: 'mdc-switch__track'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcSwitch_selected [

	self class: 'mdc-switch--selected'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcSwitch_unselected [

	self class: 'mdc-switch--unselected'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTab [

	self class: 'mdc-tab'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTabBar [

	self class: 'mdc-tab-bar'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTabIndicator [

	self class: 'mdc-tab-indicator'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTabIndicator__content [

	self class: 'mdc-tab-indicator__content'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTabIndicator__content_icon [

	self class: 'mdc-tab-indicator__content--icon'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTabIndicator__content_underline [

	self class: 'mdc-tab-indicator__content--underline'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTabIndicator_active [

	self class: 'mdc-tab-indicator--active'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTabIndicator_fade [

	self class: 'mdc-tab-indicator--fade'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTabIndicator_noTransition [

	self class: 'mdc-tab-indicator--no-transition'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTabScroller [

	self class: 'mdc-tab-scroller'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTabScroller__scrollArea [

	self class: 'mdc-tab-scroller__scroll-area'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTabScroller__scrollArea_scroll [

	self class: 'mdc-tab-scroller__scroll-area--scroll'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTabScroller__scrollContent [

	self class: 'mdc-tab-scroller__scroll-content'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTabScroller__test [

	self class: 'mdc-tab-scroller__test'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTabScroller_alignCenter [

	self class: 'mdc-tab-scroller--align-center'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTabScroller_alignEnd [

	self class: 'mdc-tab-scroller--align-end'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTabScroller_alignStart [

	self class: 'mdc-tab-scroller--align-start'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTabScroller_animating [

	self class: 'mdc-tab-scroller--animating'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTab__content [

	self class: 'mdc-tab__content'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTab__icon [

	self class: 'mdc-tab__icon'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTab__ripple [

	self class: 'mdc-tab__ripple'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTab__textLabel [

	self class: 'mdc-tab__text-label'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTab_active [

	self class: 'mdc-tab--active'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTab_minWidth [

	self class: 'mdc-tab--min-width'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTab_stacked [

	self class: 'mdc-tab--stacked'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTextField [

	self class: 'mdc-text-field'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTextFieldCharacterCounter [

	self class: 'mdc-text-field-character-counter'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTextFieldHelperLine [

	self class: 'mdc-text-field-helper-line'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTextFieldHelperText [

	self class: 'mdc-text-field-helper-text'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTextFieldHelperText_persistent [

	self class: 'mdc-text-field-helper-text--persistent'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTextFieldHelperText_validationMsg [

	self class: 'mdc-text-field-helper-text--validation-msg'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTextField__affix [

	self class: 'mdc-text-field__affix'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTextField__affix_prefix [

	self class: 'mdc-text-field__affix--prefix'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTextField__affix_suffix [

	self class: 'mdc-text-field__affix--suffix'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTextField__icon [

	self class: 'mdc-text-field__icon'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTextField__icon_leading [

	self class: 'mdc-text-field__icon--leading'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTextField__icon_trailing [

	self class: 'mdc-text-field__icon--trailing'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTextField__input [

	self class: 'mdc-text-field__input'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTextField__resizer [

	self class: 'mdc-text-field__resizer'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTextField__ripple [

	self class: 'mdc-text-field__ripple'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTextField_disabled [

	self class: 'mdc-text-field--disabled'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTextField_endAligned [

	self class: 'mdc-text-field--end-aligned'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTextField_filled [

	self class: 'mdc-text-field--filled'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTextField_focused [

	self class: 'mdc-text-field--focused'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTextField_invalid [

	self class: 'mdc-text-field--invalid'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTextField_labelFloating [

	self class: 'mdc-text-field--label-floating'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTextField_ltrText [

	self class: 'mdc-text-field--ltr-text'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTextField_noLabel [

	self class: 'mdc-text-field--no-label'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTextField_outlined [

	self class: 'mdc-text-field--outlined'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTextField_textarea [

	self class: 'mdc-text-field--textarea'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTextField_withInternalCounter [

	self class: 'mdc-text-field--with-internal-counter'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTextField_withLeadingIcon [

	self class: 'mdc-text-field--with-leading-icon'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTextField_withTrailingIcon [

	self class: 'mdc-text-field--with-trailing-icon'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTheme_background [

	self class: 'mdc-theme--background'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTheme_error [

	self class: 'mdc-theme--error'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTheme_onError [

	self class: 'mdc-theme--on-error'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTheme_onPrimary [

	self class: 'mdc-theme--on-primary'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTheme_onSecondary [

	self class: 'mdc-theme--on-secondary'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTheme_onSurface [

	self class: 'mdc-theme--on-surface'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTheme_primary [

	self class: 'mdc-theme--primary'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTheme_primaryBg [

	self class: 'mdc-theme--primary-bg'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTheme_secondary [

	self class: 'mdc-theme--secondary'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTheme_secondaryBg [

	self class: 'mdc-theme--secondary-bg'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTheme_surface [

	self class: 'mdc-theme--surface'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTheme_textDisabledOnBackground [

	self class: 'mdc-theme--text-disabled-on-background'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTheme_textDisabledOnDark [

	self class: 'mdc-theme--text-disabled-on-dark'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTheme_textDisabledOnLight [

	self class: 'mdc-theme--text-disabled-on-light'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTheme_textHintOnBackground [

	self class: 'mdc-theme--text-hint-on-background'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTheme_textHintOnDark [

	self class: 'mdc-theme--text-hint-on-dark'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTheme_textHintOnLight [

	self class: 'mdc-theme--text-hint-on-light'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTheme_textIconOnBackground [

	self class: 'mdc-theme--text-icon-on-background'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTheme_textIconOnDark [

	self class: 'mdc-theme--text-icon-on-dark'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTheme_textIconOnLight [

	self class: 'mdc-theme--text-icon-on-light'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTheme_textPrimaryOnBackground [

	self class: 'mdc-theme--text-primary-on-background'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTheme_textPrimaryOnDark [

	self class: 'mdc-theme--text-primary-on-dark'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTheme_textPrimaryOnLight [

	self class: 'mdc-theme--text-primary-on-light'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTheme_textSecondaryOnBackground [

	self class: 'mdc-theme--text-secondary-on-background'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTheme_textSecondaryOnDark [

	self class: 'mdc-theme--text-secondary-on-dark'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTheme_textSecondaryOnLight [

	self class: 'mdc-theme--text-secondary-on-light'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTooltip [

	self class: 'mdc-tooltip'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTooltipWrapper_rich [

	self class: 'mdc-tooltip-wrapper--rich'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTooltip__caretSurfaceBottom [

	self class: 'mdc-tooltip__caret-surface-bottom'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTooltip__caretSurfaceTop [

	self class: 'mdc-tooltip__caret-surface-top'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTooltip__content [

	self class: 'mdc-tooltip__content'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTooltip__contentLink [

	self class: 'mdc-tooltip__content-link'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTooltip__surface [

	self class: 'mdc-tooltip__surface'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTooltip__surfaceAnimation [

	self class: 'mdc-tooltip__surface-animation'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTooltip__title [

	self class: 'mdc-tooltip__title'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTooltip_hide [

	self class: 'mdc-tooltip--hide'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTooltip_hideTransition [

	self class: 'mdc-tooltip--hide-transition'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTooltip_multiline [

	self class: 'mdc-tooltip--multiline'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTooltip_rich [

	self class: 'mdc-tooltip--rich'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTooltip_richActions [

	self class: 'mdc-tooltip--rich-actions'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTooltip_showing [

	self class: 'mdc-tooltip--showing'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTooltip_showingTransition [

	self class: 'mdc-tooltip--showing-transition'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTooltip_shown [

	self class: 'mdc-tooltip--shown'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTopAppBar [

	self class: 'mdc-top-app-bar'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTopAppBar__actionItem [

	self class: 'mdc-top-app-bar__action-item'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTopAppBar__navigationIcon [

	self class: 'mdc-top-app-bar__navigation-icon'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTopAppBar__row [

	self class: 'mdc-top-app-bar__row'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTopAppBar__section [

	self class: 'mdc-top-app-bar__section'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTopAppBar__section_alignEnd [

	self class: 'mdc-top-app-bar__section--align-end'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTopAppBar__section_alignStart [

	self class: 'mdc-top-app-bar__section--align-start'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTopAppBar__title [

	self class: 'mdc-top-app-bar__title'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTopAppBar_dense [

	self class: 'mdc-top-app-bar--dense'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTopAppBar_denseFixedAdjust [

	self class: 'mdc-top-app-bar--dense-fixed-adjust'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTopAppBar_denseProminentFixedAdjust [

	self class: 'mdc-top-app-bar--dense-prominent-fixed-adjust'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTopAppBar_fixed [

	self class: 'mdc-top-app-bar--fixed'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTopAppBar_fixedAdjust [

	self class: 'mdc-top-app-bar--fixed-adjust'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTopAppBar_fixedScrolled [

	self class: 'mdc-top-app-bar--fixed-scrolled'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTopAppBar_prominent [

	self class: 'mdc-top-app-bar--prominent'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTopAppBar_prominentFixedAdjust [

	self class: 'mdc-top-app-bar--prominent-fixed-adjust'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTopAppBar_short [

	self class: 'mdc-top-app-bar--short'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTopAppBar_shortCollapsed [

	self class: 'mdc-top-app-bar--short-collapsed'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTopAppBar_shortFixedAdjust [

	self class: 'mdc-top-app-bar--short-fixed-adjust'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTopAppBar_shortHasActionItem [

	self class: 'mdc-top-app-bar--short-has-action-item'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTouchTargetWrapper [

	self class: 'mdc-touch-target-wrapper'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTypography [

	self class: 'mdc-typography'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTypography_body1 [

	self class: 'mdc-typography--body1'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTypography_body2 [

	self class: 'mdc-typography--body2'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTypography_button [

	self class: 'mdc-typography--button'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTypography_caption [

	self class: 'mdc-typography--caption'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTypography_headline1 [

	self class: 'mdc-typography--headline1'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTypography_headline2 [

	self class: 'mdc-typography--headline2'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTypography_headline3 [

	self class: 'mdc-typography--headline3'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTypography_headline4 [

	self class: 'mdc-typography--headline4'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTypography_headline5 [

	self class: 'mdc-typography--headline5'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTypography_headline6 [

	self class: 'mdc-typography--headline6'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTypography_overline [

	self class: 'mdc-typography--overline'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTypography_subtitle1 [

	self class: 'mdc-typography--subtitle1'
]

{ #category : #'*Material-Web-Core' }
WATagBrush >> mdcTypography_subtitle2 [

	self class: 'mdc-typography--subtitle2'
]
