rendering
products

	^#(
('assets/ginger-scarf.jpg' 'Ginger scarf')
('assets/blue-stone-mug.jpg' 'Blue stone mug')
('assets/cerise-scallop.jpg' 'Cerise scallop tee')
('assets/chambray-napkins.jpg' 'Chambray napkins')
('assets/fine-lines.jpg' 'Fine lines tee')
('assets/garden-strand.jpg' 'Garden strand')
('assets/gatsby-hat.jpg' 'Gatsby hat')
('assets/gilt-desk-trio.jpg' 'Gilt desk trio')
('assets/kitchen-quattro.jpg' 'Kitchen quattro')
('assets/seabreeze-sweater.jpg' 'Seabreeze sweater')
('assets/shrug-bag.jpg' 'Shrug bag')
('assets/stella-sunglasses.jpg' 'Stella sunglasses')
('assets/surf-and-perf.jpg' 'Surf and perf shirt')
('assets/vagabond-sack.jpg' 'Vagabond sack')
('assets/walter-henley.jpg' 'Walter henley (white)')
('assets/weave-keyring.jpg' 'Weave keyring')
	)