rendering - button
renderButtonHeroOn: html

	html section
		class: 'hero';
		with: [html html: '<button class="mdc-button mdc-ripple-upgraded" style="--mdc-ripple-fg-size:45.1781px; --mdc-ripple-fg-scale:2.06871; --mdc-ripple-fg-translate-start:17.0401px, -3.64006px; --mdc-ripple-fg-translate-end:15.0594px, -4.58906px;">
          Flat
        </button>
        <button class="mdc-button mdc-button--raised mdc-ripple-upgraded" style="--mdc-ripple-fg-size:57.3656px; --mdc-ripple-fg-scale:1.95522;">
          Raised
        </button>
        <small class="note">Note: "secondary" was previously called "accent" in the Material spec.</small>']
